// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOz3MW4oTG1xLSDkK4cAaH4vuUJJSKjQ',
    appId: '1:176625060286:web:a47ff9a18ee9899078d1ef',
    messagingSenderId: '176625060286',
    projectId: 'flownote-2914a',
    authDomain: 'flownote-2914a.firebaseapp.com',
    storageBucket: 'flownote-2914a.firebasestorage.app',
    measurementId: 'G-L9QW42R1CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqv5QnyYTax0dleQ64IhGxIATS-NOPw88',
    appId: '1:176625060286:android:9465fd532e6b6ac178d1ef',
    messagingSenderId: '176625060286',
    projectId: 'flownote-2914a',
    storageBucket: 'flownote-2914a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqlIoKQw2fJuj8im5HOs5fZT2TnqW0lA',
    appId: '1:176625060286:ios:8d8e8208dc41ecfb78d1ef',
    messagingSenderId: '176625060286',
    projectId: 'flownote-2914a',
    storageBucket: 'flownote-2914a.firebasestorage.app',
    iosBundleId: 'com.example.flownote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqlIoKQw2fJuj8im5HOs5fZT2TnqW0lA',
    appId: '1:176625060286:ios:8d8e8208dc41ecfb78d1ef',
    messagingSenderId: '176625060286',
    projectId: 'flownote-2914a',
    storageBucket: 'flownote-2914a.firebasestorage.app',
    iosBundleId: 'com.example.flownote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqOz3MW4oTG1xLSDkK4cAaH4vuUJJSKjQ',
    appId: '1:176625060286:web:b0f1c204b38b5d4978d1ef',
    messagingSenderId: '176625060286',
    projectId: 'flownote-2914a',
    authDomain: 'flownote-2914a.firebaseapp.com',
    storageBucket: 'flownote-2914a.firebasestorage.app',
    measurementId: 'G-YQFP3K80DG',
  );
}
